import React from 'react';

function Asian () {
  return (
    <div>
      [asian]
      UDON
      (SERVED WITH BROCCOLI, SCALLIONS, CARROTS, SEAWEED, YUBU) I SOBA $1.00 EXTRA
      $6.95
      VEGETABLE
      $7.95
      TOFU
      $7.95
      CHICKEN
      $8.95
      BEEF
      $8.95
      SHRIMP TEMPURA
      $8.95
      SHUMAI
      RAMEN
      (SERVED WITH BROCCOLI, SCALLION, CARROT) I EGG $1.00 EXTRA
      $6.95
      VEGETABLE
      $7.95
      CHICKEN
      $8.95
      BEEF
      $8.95
      SEAFOOD
      BIBIMBAP
      (SERVED WITH WHITE RICE, SEASONED VEGETABLES, FRIED EGG AND HOT PASTE) I BROWN RICE $1.00 EXTRA
      $7.95
      VEGETABLE
      $8.45
      TOFU
      $8.95
      CHICKEN
      $9.95
      BEEF
      TERIYAKI
      (SERVED WITH BROCCOLI, CARROTS, ONIONS, MUSHROOMS) I BROWN RICE OR YAKI UDON $1.00 EXTRA
      $8.45
      CHICKEN TERIYAKI
      $8.45
      TOFU TERIYAKI
      $9.45
      BEEF TERIYAKI
      $9.45
      SHRIMP TERIYAKI
      $9.45
      SALMON TERIYAKI
      STIR FRY
      $8.95 I BROWN RICE, SOBA, SHRIMP $1.00 EXTRA
      (STEP 1) CHOOSE YOUR NOODLE OR RICE
      WHITE RICE, BROWN RICE, SOBA, UDON, RICE NOODLE, GLASS NOODLE
      (STEP 2) CHOOSE A PROTEIN
      CHICKEN, BEEF, SHRIMP
      (STEP 3) CHOOSE VEGETABLES
      BOK CHOY, BEAN SPROUTS, BROCCOLI, CARROTS, MUSHROOMS, SCALLIONS, ONIONS, SNOW PEAS, ZUCCHINI, CILANTRO
      (STEP 4) CHOOSE A SAUCE
      TERIYAKI, ASIAN BBQ, GARLIC, SWEET & SOUR, LEMON, COCONUT THAI CURRY
    </div>
  )
}

export default Asian;
