import React from 'react';

function Salads () {
  return (
    <div>
      [salad]
      <h1>HOMESTYLE SALADS</h1>
      GARDEN SALAD
      ROMAINE LETTUCE, TOMATOES, CUCUMBERS, CARROTS, MIXED PEPPERS, BLACK OLIVES, HOUSE DRESSING
      SM $3.95 / LG $6.95
      ADD GRILLED CHICKEN, TUNA SALAD OR CHICKEN SALAD
      $1.50
      CAESAR SALAD
      ROMAINE LETTUCE, CROUTON, PARMESAN CHEESE, CAESAR DRESSING
      SM $3.95 / LG $6.95
      GRILLED CHICKEN CAESAR SALAD
      GRILLED CHICKEN, ROMAINE LETTUCE, PARMESAN CHEESE, CROUTONS, CAESAR DRESSING
      LG $7.95
      COBB SALAD
      GRILLED CHICKEN, ROMAINE LETTUCE, TOMATOES, BACON, BOILED EGG, BLUE CHEESE
      LG $7.95

      <h1>CUSTOM SALADS</h1>
      <h5>SMALL $7.95 / LARGE $8.95</h5>
      (STEP 1) CHOOSE A GREEN
      CRISPY ROMAIN / BABY SPINACH/ ORGANIC MESCLUN, KALE
      (STEP 2) CHOOSE A PROTEIN
      TUNA SALAD/ TURKEY / HAM / GRILLED CHICKEN / CRISPY CHICKEN / ALBACORE TUNA / CHICKEN SALAD
      (STEP 3) CHOOSE 2 PREMIUM INGREDIENTS
      GOLDEN RAISIN, BLUE CHEESE CRUMBS, SUNFLOWER SEEDS, FETA CHEESE, TOASTED PINE NUTS, WALNUTS, CHEDDAR CHEESE, PARMESAN CHEESE, DRIED CRANBERRIES, FRESH MOZZARELLA, BOILED EGG, SUN DRIED TOMATOES, EGG WHITE, AVOCADO
      (STEP 4) CHOOSE UNLIMITED VEGETABLES
      BLACK OLIVE, BLACK BEANS, KALAMETA OLIVE, MUSHROOMS, CORN, ARTICHOKE HEARTS, PLUM TOMATOES, CHINESE NOODLES, ALFALFA SPROUTS, JALAPENOS, GREEN PEAS, BROCCOLI FLORETS, CHICK PEAS, BELL PEPPERS, CELERY, CROUTON, CHERRY TOMATOES, STRING BEANS, GRANNY SMITH APPLES, MANDARIN ORANGE, RED BEETS, ROASTED ZUCCHINI, ASPARAGUS, ROASTED EGGPLANT, EDAMAME, PORTOBELLO MUSHROOMS, ROASTED RED PEPPERS, BRUSSEL SPROUTS, HEARTS OF PALM
      (STEP 5) CHOOSE A DRESSING
      BLUE CHEESE, RUSSIAN, CREAMY ITALIAN, FRENCH, HOUSE CAESAR, HONEY DIJON, LOW FAT HONEY MUSTARD, LIT ITALIAN, BALSAMIC VINAIGRETTE, ASIAN SESAME GINGER, CLASSIC RANCH, LITE RANCH, RASPBERRY VINAIGRETTE, BALSAMIC VINEGAR, LEMON JUICE, OLIVE OIL, RED WINE VINEGAR
    </div>
  )
}

export default Salads;
