import React from 'react';

function Sandwiches () {
  return (
    <div>
      [sandwich]
      <h1>SIGNATURE COLD SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <ul>
        <li>
          <h3>ITALIAN</h3>
          GENOA SALAMI, CAPICOLA, PROVOLONE CHEESE, LETTUCE, TOMATOES, ONIONS, HOT PEPPERS, OIL & VINEGAR
        </li>
        <li>
          <h3>AMERICAN</h3>
          VIRGINIA HAM, BLACK FOREST HAM, AMERICAN CHEESE, LETTUCE, TOMATOES, MAYO
        </li>
        <li>
          <h3>TABLETIME</h3>
          SMOKED TURKEY, CORNED BEEF, COLESLAW, SWISS CHEESE, RUSSIAN DRESSING
        </li>
        <li>
          <h3>CT</h3>
          TURKEY BREAST, CORNED BEEF, COLESLAW, SWISS CHEESE, RUSSIAN DRESSING
        </li>
        <li>
          <h3>GREEN TURKEY</h3>
          TURKEY BREAST, BRIE CHEESE, SLICED GRANNY SMITH APPLE, LETTUCE, HONEY MUSTARD
        </li>
      </ul>

      <h1>VEGETARIAN SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <ul>
        <li>
          MOZZARELLA DELIGHT
          FRESH MOZZARELLA CHEESE ROASTED RED PEPPERS, TOMATO, BASIL, ITALIAN DRESSING
        </li>
        <li>
          LITE DELIGHTS
          GRILLED VEGETABLES, GREEN SQUASH, YELLOW SQUASH, EGGPLANT, CARROTS, FRESH MOZZARELLA CHEESE, ROASTED RED PEPPERS, HUMMUS TAHINI SAUCE
        </li>
        <li>
          VEGETARIAN SPECIAL
          AVOCADO, ROMAINE LETTUCE, TOMATOES, CARROTS, CUCUMBERS, ALFAFA SPROUTS, SHREDDED RED CABBAGE, SWEET PEPPERS, HONEY MUSTARD
        </li>
        <li>
          EGGPLANT & ZUCCHINI
          EGGPLANTS & ZUCCHINI MARINATED WITH BALSAMIC VINEGAR, ROASTED RED PEPPERS, SMOKED MOZZARELLA CHEESE, HONEY DIJON MUSTARD
        </li>
      </ul>

      <h1>SIGNATURE HOT SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <ul>
        <li>
          "T" COMBO
          HOT PASTRAMI, CORNED BEEF, SWISS CHEESE, COLE SLAW, RUSSIAN DRESSING
        </li>
        <li>
          THE PHILLY
          GRILLED PHILLY STEAK, MELTED AMERICAN CHEESE, GRILLED ONIONS AND PEPPERS
        </li>
        <li>
          THE SMOKY
          SMOKED HAM, SMOKED TURKEY, SWISS CHEESE, COLESLAW, RUSSIAN DRESSING
        </li>
        <li>
          THE MAXIMUS
          GRILLED SMOKED TURKEY, MELTED PEPPER JACK CHEESE, CRISPY BACON, SUNDRIED TOMATO PASTE
        </li>
        <li>
          THE AMAZING
          OVEN ROASTED FRESH TURKEY, MELTED SWISS CHEESE, ROASTED PEPPERS, CRANBERRY SAUCE
        </li>
      </ul>

      <h1>HOT SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <ul>
        <li>
          THE CLASSIC
          GRILLED CHICKEN BREAST, FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE, ROASTED RED PEPPERS
        </li>
        <li>
          THE CHICAVO
          GRILLED CHICKEN BREAST, AVOCADO, ROASTED RED PEPPERS, MESCLUN, RANCH DRESSING
        </li>
        <li>
          THE TOBASCO
          GRILLED CHICKEN BREAST, MELTED FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE, HOT PEPPERS, TABASCO SAUCE
        </li>
        <li>
          TERIYAKI CHICKEN
          GRILLED CHICKEN BREAST, MELTED FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE, TOMATO, TERIYAKI SAUCE
        </li>
        <li>
          HONEY BBQ CHICKEN
          GRILLED CHICKEN BREAST, MELTED FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE
        </li>
      </ul>
    </div>
  )
}

export default Sandwiches;
