import React from 'react';

function Sandwiches () {
  return (
    <div>
      [sandwich]
      <h1>SIGNATURE COLD SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <div>
        <h3>ITALIAN</h3>
        GENOA SALAMI, CAPICOLA, PROVOLONE CHEESE, LETTUCE, TOMATOES, ONIONS, HOT PEPPERS, OIL & VINEGAR
      </div>
      <div>
        <h3>AMERICAN</h3>
        VIRGINIA HAM, BLACK FOREST HAM, AMERICAN CHEESE, LETTUCE, TOMATOES, MAYO
      </div>
      <div>
        <h3>TABLETIME</h3>
        SMOKED TURKEY, CORNED BEEF, COLESLAW, SWISS CHEESE, RUSSIAN DRESSING
      </div>
      <div>
        <h3>CT</h3>
        TURKEY BREAST, CORNED BEEF, COLESLAW, SWISS CHEESE, RUSSIAN DRESSING
      </div>
      <div>
        <h3>GREEN TURKEY</h3>
        TURKEY BREAST, BRIE CHEESE, SLICED GRANNY SMITH APPLE, LETTUCE, HONEY MUSTARD
      </div>

      <h1>VEGETARIAN SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <div>
        MOZZARELLA DELIGHT
        FRESH MOZZARELLA CHEESE ROASTED RED PEPPERS, TOMATO, BASIL, ITALIAN DRESSING
      </div>
      <div>
        LITE DELIGHTS
        GRILLED VEGETABLES, GREEN SQUASH, YELLOW SQUASH, EGGPLANT, CARROTS, FRESH MOZZARELLA CHEESE, ROASTED RED PEPPERS, HUMMUS TAHINI SAUCE
      </div>
      <div>
        VEGETARIAN SPECIAL
        AVOCADO, ROMAINE LETTUCE, TOMATOES, CARROTS, CUCUMBERS, ALFAFA SPROUTS, SHREDDED RED CABBAGE, SWEET PEPPERS, HONEY MUSTARD
      </div>
      <div>
        EGGPLANT & ZUCCHINI
        EGGPLANTS & ZUCCHINI MARINATED WITH BALSAMIC VINEGAR, ROASTED RED PEPPERS, SMOKED MOZZARELLA CHEESE, HONEY DIJON MUSTARD
      </div>

      <h1>SIGNATURE HOT SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <div>
        "T" COMBO
        HOT PASTRAMI, CORNED BEEF, SWISS CHEESE, COLE SLAW, RUSSIAN DRESSING
      </div>
      <div>
        THE PHILLY
        GRILLED PHILLY STEAK, MELTED AMERICAN CHEESE, GRILLED ONIONS AND PEPPERS
      </div>
      <div>
        THE SMOKY
        SMOKED HAM, SMOKED TURKEY, SWISS CHEESE, COLESLAW, RUSSIAN DRESSING
      </div>
      <div>
        THE MAXIMUS
        GRILLED SMOKED TURKEY, MELTED PEPPER JACK CHEESE, CRISPY BACON, SUNDRIED TOMATO PASTE
      </div>
      <div>
        THE AMAZING
        OVEN ROASTED FRESH TURKEY, MELTED SWISS CHEESE, ROASTED PEPPERS, CRANBERRY SAUCE
      </div>

      <h1>HOT SANDWICHES</h1>
      <h5>SLICED BREAD or ROLL $7.49 / WRAPS or HERO $8.99</h5>
      <div>
        THE CLASSIC
        GRILLED CHICKEN BREAST, FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE, ROASTED RED PEPPERS
      </div>
      <div>
        THE CHICAVO
        GRILLED CHICKEN BREAST, AVOCADO, ROASTED RED PEPPERS, MESCLUN, RANCH DRESSING
      </div>
      <div>
        THE TOBASCO
        GRILLED CHICKEN BREAST, MELTED FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE, HOT PEPPERS, TABASCO SAUCE
      </div>
      <div>
        TERIYAKI CHICKEN
        GRILLED CHICKEN BREAST, MELTED FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE, TOMATO, TERIYAKI SAUCE
      </div>
      <div>
        HONEY BBQ CHICKEN
        GRILLED CHICKEN BREAST, MELTED FRESH MOZZARELLA CHEESE, GRILLED ONIONS, ROMAINE LETTUCE
      </div>
    </div>
  )
}

export default Sandwiches;
