import React from 'react';

function Wraps () {
  return (
    <div>
      [wrap]
      <h1>WRAPS</h1>
      <h5>$7.95</h5>
      CHICKEN CAESAR
      GRILLED CHICKEN, ROMAINE LETTUCE, ROMANO CHEESE, CROUTONS, CAESAR DRESSING
      CALIFORNIA
      GRILLED CHICKEN, LETTUCE, TOMATO, AVOCADO, ROASTED RED PEPPERS, RANCH DRESSING
      CRISPY CHICKEN CUTLET
      BREADED CHICKEN CUTLET, AVOCADO, TOMATO, BABY SPINACH, CHIPOTLE SPREAD
      VEGETARIAN
      GRILLED SQUASH, ROASTED PORTOBELLO MUSHROOMS, ROASTED RED PEPPERS, FRESH MOZZARELLA CHEESE, BALSAMIC VINEGAR
      TUNA SALAD
      FRESH TUNA SALAD, LEAF LETTUCE, TOMATOES, SPROUT
      TURKEY CLUB
      OVEN ROASTED TURKEY, BACON, LETTUCE, TOMATOES, MAYO
      BISTRO
      ROAST BEEF, OVEN ROASTED TURKEY, MUENSTER CHEESE, LETTUCE, TOMATOES, RUSSIAN DRESSING
    </div>
  )
}

export default Wraps;
